export const UPDATE_GAME_STEP = 'XMAS/UPDATE_GAME_STEP'
export const UPDATE_CURRENT_GAME_NAME = 'XMAS/UPDATE_CURRENT_GAME_NAME'
export const SCORE_TEAM = 'XMAS/SCORE_TEAM'
export const UNSCORE_TEAM = 'XMAS/UNSCORE_TEAM'
