export const UPDATE_GAME_STEP = 'XMAS/UPDATE_GAME_STEP'
export const UPDATE_CURRENT_GAME_NAME = 'XMAS/UPDATE_CURRENT_GAME_NAME'
export const UPDATE_SCORE_TEAM_1 = 'XMAS/UPDATE_SCORE_TEAM_1'
export const UPDATE_SCORE_TEAM_2 = 'XMAS/UPDATE_SCORE_TEAM_2'
